1;

doPlots = 1;

if ( ~exist('srvi2','var') || isempty(srvi2) )
  srvi2 = load_station_data('srvi2');
end;

srvi2 = calc_kd_daily(srvi2, 'bic_surf_par', 'bic_shallow_par', 2);
srvi2 = calc_kd_daily(srvi2, 'bic_surf_305nm', 'bic_shallow_305nm', 2);
srvi2 = calc_kd_daily(srvi2, 'bic_surf_par', 'bic_deep_par', 5.35);
srvi2 = calc_kd_daily(srvi2, 'bic_surf_305nm', 'bic_deep_305nm', 5.35);

if ( doPlots )
multiplot_station(srvi2, ...
                  { 'bic_surf_par_daily_mean', ...
                    'bic_shallow_par_daily_mean', ...
                    'del_1_day_bic_surf_par_bic_shallow_par', ...
                    'kd_1_day_bic_surf_par_bic_shallow_par' }, ...
                  'SRVI2 \DeltaPAR_1_m vs. Kd_P_A_R_1_m', [], ...
                  { '\mu_1_d(PAR_s_f_c)', ...
                    '\mu_1_d(PAR_1_m)', ...
                    '\DeltaPAR_1_m', ...
                    'Kd_P_A_R_1_m' } ...
                  );
print('-dpng','figs/srvi2_delta_par_vs_kd_par_1m.png');

multiplot_station(srvi2, ...
                  { 'bic_surf_305nm_daily_mean', ...
                    'bic_shallow_305nm_daily_mean', ...
                    'del_1_day_bic_surf_305nm_bic_shallow_305nm', ...
                    'kd_1_day_bic_surf_305nm_bic_shallow_305nm' }, ...
                  'SRVI2 \DeltaUVB_1_m vs. Kd_U_V_B_1_m', [], ...
                  { '\mu_1_d(305nm_s_f_c)', ...
                    '\mu_1_d(305nm_1_m)', ...
                    '\DeltaUVB_1_m', ...
                    'Kd_U_V_B_1_m' } ...
                  );
print('-dpng','figs/srvi2_delta_uvb_vs_kd_uvb_1m.png');

multiplot_station(srvi2, ...
                  { 'bic_surf_par_daily_mean', ...
                    'bic_deep_par_daily_mean', ...
                    'del_1_day_bic_surf_par_bic_deep_par', ...
                    'kd_1_day_bic_surf_par_bic_deep_par' }, ...
                  'SRVI2 \DeltaPAR_5_m vs. Kd_P_A_R_5_m', [], ...
                  { '\mu_1_d(PAR_s_f_c)', ...
                    '\mu_1_d(PAR_5_m)', ...
                    '\DeltaPAR_5_m', ...
                    'Kd_P_A_R_5_m' } ...
                  );
print('-dpng','figs/srvi2_delta_par_vs_kd_par_5m.png');

multiplot_station(srvi2, ...
                  { 'bic_surf_305nm_daily_mean', ...
                    'bic_deep_305nm_daily_mean', ...
                    'del_1_day_bic_surf_305nm_bic_deep_305nm', ...
                    'kd_1_day_bic_surf_305nm_bic_deep_305nm' }, ...
                  'SRVI2 \DeltaUVB_5_m vs. Kd_U_V_B_5_m', [], ...
                  { '\mu_1_d(305nm_s_f_c)', ...
                    '\mu_1_d(305nm_5_m)', ...
                    '\DeltaUVB_5_m', ...
                    'Kd_U_V_B_5_m' } ...
                  );
print('-dpng','figs/srvi2_delta_uvb_vs_kd_uvb_5m.png');
end;

clear doPlots;
