function stn = build_factories(stn)
%function stn = build_factories(stn)
%
% Add some additional fact-factories to the MOLASSES REEF (mlrf1) station
% data struct 'stn' - factories that were never implemented in ICON/G2.
% NOTE: This is meant to be called IN ADDITION TO 'load_factories'.
%
% Last Saved Time-stamp: <Thu 2010-02-04 21:10:12 Eastern Standard Time gramer>
%

  stn.factories.parsurf.variable = 'seandbc';
  stn.factories.parsurf.fuzzies = ...
      { ...
          { 'drastic-low',	[ 15	17 ] }, ...
          { 'very-low',		[ 17	19 ] }, ...
          { 'low',		[ 19	21 ] }, ...
          { 'somewhat-low',	[ 21	24 ] }, ...
          { 'average',		[ 24	29 ] }, ...
          { 'somewhat-high',	[ 29	31.4 ] }, ...
          { 'high',		[ 31.4	32 ] }, ...
          { 'very-high',	[ 32	33 ] }, ...
          { 'drastic-high',	[ 33	34 ] }, ...
      };

  stn.factories.parsurf.variable = 'licor_surf_par';
  stn.factories.parsurf.fuzzies = ...
      { ...
          { 'drastic-low',	[ 0	50 ] }, ...
          { 'very-low',		[ 50	100 ] }, ...
          { 'low',		[ 100	300 ] }, ...
          { 'somewhat-low',	[ 300	500 ] }, ...
          { 'average',		[ 500	700 ] }, ...
          { 'somewhat-high',	[ 700	800 ] }, ...
          { 'high',		[ 800	1000 ] }, ...
          { 'very-high',	[ 1000	1200 ] }, ...
          { 'drastic-high',	[ 1200	1400 ] }, ...
      };

  stn.factories = rmfield(stn.factories, 'parsurf');
  stn.factories.parsurf.variable = 'model_surf_par';
  stn = model_surf_par('mlrf1', stn, 1987, 2008);
  stn.factories.parsurf.fuzzies = ...
      { ...
          { 'drastic-low',	[ 0	900 ] }, ...
          { 'very-low',		[ 900	1000 ] }, ...
          { 'low',		[ 1000	1100 ] }, ...
          { 'somewhat-low',	[ 1100	1200 ] }, ...
          { 'average',		[ 1200	1500 ] }, ...
          { 'somewhat-high',	[ 1500	1550 ] }, ...
          { 'high',		[ 1550	1600 ] }, ...
          { 'very-high',	[ 1600	1650 ] }, ...
          { 'drastic-high',	[ 1650	1700 ] }, ...
      };

  stn.factories.windsp.variable = 'wind2_speed';
  stn.factories.windsp.fuzzies = ...
      { ...
          { 'drastic-low',	[ 0	2 ] }, ...
          { 'very-low',		[ 2	4 ] }, ...
          { 'low',		[ 4	7 ] }, ...
          { 'somewhat-low',	[ 7	10 ] }, ...
          { 'average',		[ 10	21 ] }, ...
          { 'somewhat-high',	[ 21	33 ] }, ...
          { 'high',		[ 33	40 ] }, ...
          { 'very-high',	[ 40	64 ] }, ...
          { 'drastic-high',	[ 64	100 ] }, ...
      };

return;
