function trueOrFalse = is_valid_ts(ts)
%function trueOrFalse = is_valid_ts(ts)
%
% A "valid" time series TS has equal-length row-vector fields TS.date and
% TS.data (data may be a row-cellstr), TS.date is monotonically increasing
% and numeric and has only "valid" DATENUMs (between 0 and 1e6), and TS.data
% has at least one valid (non-empty string or finite/non-NaN numeric) value.
% 
% Last Saved Time-stamp: <Sat 2011-04-16 14:04:51  Lew.Gramer>

  trueOrFalse = ( is_ts(ts) && all(size(ts.date) == size(ts.data)) && ...
                  (ndims(ts.date)==2) && (size(ts.date,2) == 1) && ...
                  all(0 < ts.date & ts.date < 1e6) && ...
                  all(diff(ts.date) > eps) && ...
                  ( (isnumeric(ts.data) && any(isfinite(ts.data))) || ...
                    (iscellstr(ts.data) && any(cellfun(@length,ts.data)>0)) ...
                    ) ...
                  );

return;
