function ef = load_ef_mcs()
%function ef = load_ef_mcs()
%
% Load ecoforecast model for "mass-coral-stress"
%
% Last Saved Time-stamp: <Thu 2009-02-19 19:58:32 Eastern Standard Time gramer>
%

  ef.name = 'Mass-Coral-Stress';
  ef.shortdesc = 'Environmental stress on coral community may be conducive to bleaching';
  ef.desc = [ 'Thermal-, photo-, and/or haline-stress on coral community are extreme' ...
              'enough, singly or in combination, that they may be conducive to' ...
              'bleaching and possible mortality among multiple coral species.' ...
            ];

%   ef.rules.it.facts = { { 'bleaching_seatemp' } };
%   ef.rules.it.fuzzies = {{'drastic-high'}};

%   ef.rules.itw.facts = { { 'bleaching_seatemp' } , ...
%                       { 'windsp', 'windsp2', 'wxtwindsp' } };
%   ef.rules.itw.fuzzies = {{'very-high','drastic-high'}, ...
%                       {'drastic-low','very-low','low'}};

% %   ef.rules.itwt.facts = { { 'bleaching_seatemp' } , ...
% %                       { 'windsp', 'windsp2', 'wxtwindsp' } , ...
% %                       'tide1m' };
% %   ef.rules.itwt.fuzzies = {{'high','very-high','drastic-high'}, ...
% %                       {'drastic-low','very-low','low'}, ...
% %                       {'drastic-low','very-low','low'}};

%   ef.rules.itl.facts = { { 'bleaching_seatemp' } , ...
%                       'parsurf' };
%   ef.rules.itl.fuzzies = {{'very-high','drastic-high'}, ...
%                       {'very-high','drastic-high'}};

%   ef.rules.itlw.facts = { { 'bleaching_seatemp' } , ...
%                       'parsurf' , ...
%                       { 'windsp', 'windsp2', 'wxtwindsp' } };
%   ef.rules.itlw.fuzzies = {{'high','very-high','drastic-high'}, ...
%                       {'high','very-high','drastic-high'}, ...
%                       {'drastic-low','very-low','low'}};

% %   ef.rules.itlwt.facts = { { 'bleaching_seatemp' } , ...
% %                       'parsurf', ...
% %                       { 'windsp', 'windsp2', 'wxtwindsp' } , ...
% %                       'tide1m' };
% %   ef.rules.itlwt.fuzzies = {{'high','very-high','drastic-high'}, ...
% %                       {'high','very-high','drastic-high'}, ...
% %                       {'drastic-low','very-low','low'}, ...
% %                       {'drastic-low','very-low','low'}};

%   ef.rules.itd.facts = { { 'bleaching_seatemp' } , ...
%                       { 'windsp_3day', 'windsp2_3day', 'wxtwindsp_3day' } };
%   ef.rules.itd.fuzzies = {{'very-high','drastic-high'}, ...
%                       {'drastic-low','very-low','low'}};

%   ef.rules.itld.facts = { { 'bleaching_seatemp' } , ...
%                       'parsurf', ...
%                       { 'windsp_3day', 'windsp2_3day', 'wxtwindsp_3day' } };
%   ef.rules.itld.fuzzies = {{'high','very-high','drastic-high'}, ...
%                       {'high','very-high','drastic-high'}, ...
%                       {'drastic-low','very-low','low'}};

  ef.rules.mmit.facts = { {'bleaching_seatemp_monthly','seandbc_monthly','sea1m_monthly'} };
  ef.rules.mmit.fuzzies = {{'high','very-high','drastic-high'}};

return;
