function stn = remove_diag_fields(stn)
%function stn = remove_diag_fields(stn)
%
% Remove fields from (newly loaded) station struct STN whose sole purpose is
% station or instrument diagnostics (e.g., voltages, data counts).
%
% Last Saved Time-stamp: <Tue 2015-04-28 15:58:49 Eastern Daylight Time gramer>

  flds = { ...
      'Name', ...
      'Sig', ...
      'Batt', ...
      'PTemp', ...
      'Id', ...
      'Jyear', ...
      'Jday', ...
      'Minute', ...
      'Second', ...
      'TQual', ...
      'FreqOff', ...
      'ModInd', ...
      'DQual', ...
      'Channel', ...
      'GOESSat', ...
      'Uplink', ...
      'MLength', ...
      'dlYear', ...
      'dlJday', ...
      'dlTime', ...
      'PSig', ...
      'ST_BattV', ...
      'ST_AveGPS', ...
      'LM_Fpower', ...
      'LM_Rpower', ...
      'LM_BattV', ...
      'LM_GPStim', ...
      'BattMin', ...
      'BattMax', ...
      'BattV', ...
      'SuppV', ...
      'WiperV', ...
      'InCurr', ...
      'dlCnt', ...
      'TX_Errors', ...
      'Station', ...
      'Station_Timestamp', ...
      'TimeStamp', ...
      'stnYear', ...
      'stnJday', ...
      'stnTime', ...
      'TX_ErrCmd', ...
      'TX_ErrCod', ...
      ...
      'cfmStat', ...
      'cfmRecs', ...
      'cfmDays', ...
      ...
      'BICSVlt', ...
      'BICSTmp', ...
      'BICUVlt', ...
      'BICUTmp', ...
      'BICDVlt', ...
      'BICDTmp', ...
      ...
      'CTBatt', ...
      'CTCnt', ...
      'CTCount', ...
      'CTDBatt', ...
      'CTDCnt', ...
      'CTDCount', ...
      ...
      'cp_temp', ...
      'cp_hdrcnt', ...
      'cp_detcnt', ...
      'cp_errcnt', ...
      'cp_b02_01', ...
      'cp_b02_02', ...
      'cp_b02_03', ...
      'cp_b02_04', ...
      'cp_b02_05', ...
      'cp_b02_06', ...
      'cp_b02_07', ...
      'cp_b02_08', ...
      'cp_b02_09', ...
      'cp_b02_10', ...
      'cp_b07_01', ...
      'cp_b07_02', ...
      'cp_b07_03', ...
      'cp_b07_04', ...
      'cp_b07_05', ...
      'cp_b07_06', ...
      'cp_b07_07', ...
      'cp_b07_08', ...
      'cp_b07_09', ...
      'cp_b07_10', ...
      'cp_b28_01', ...
      'cp_b28_02', ...
      'cp_b28_03', ...
      'cp_b28_04', ...
      'cp_b28_05', ...
      'cp_b28_06', ...
      'cp_b28_07', ...
      'cp_b28_08', ...
      'cp_b28_09', ...
      'cp_b28_10', ...
      ...
      'FI0', ...
      'FIJunk0', ...
      'FIJunk1', ...
      'FIJunk2', ...
      'FIJunk3', ...
      'FIJunk4', ...
      'FIJunk5', ...
      'FIJunk6', ...
      'FIJunk7', ...
      'FIJunk8', ...
      'FIJunk9', ...
      'FJ0', ...
      ...
      'WxCnt', ...
      'WxRefVolt', ...
      'WxSupVolt', ...
      'WxVolt', ...
         };

  %fldix = isfield(stn, flds);
  fldnms = fieldnames(stn);
  fldix = find(ismember(lower(fldnms), lower(flds)));

  % Remove all matching fields, regardless of case
  stn = rmfield(stn, fldnms(fldix));

return;
