function stn = translate_station_name(colhdr,findAliases)
%function stn = translate_station_name(colhdr,findAliases)
%
% Stations have changed 5-character designations at various times over the
% years: translate all variants of a station's 5-char code into one canonical
% value for that site, e.g., 'CMRC2' and 'CMRC3' both translate as 'LSIB4'.
% If optional second arg FINDALIASES is True, return instead a cell array of
% strings with all past aliases for the specified station.
%
% Last Saved Time-stamp: <Thu 2011-10-06 10:55:12 Eastern Daylight Time gramer>

  % Column headers from 10-char col files, Web-XLS files, etc.
  stns = ...
      { ...
          'CMRC' ,			'LSIB4'  ; ...
          'CMRC1' ,			'LSIB4'  ; ...
          'CMRC2' ,			'LSIB4'  ; ...
          'CMRC3' ,			'LSIB4'  ; ...
          ...
          'LCCI1' ,			'LCIY2'  ; ...
          ...
          'MLRF2' ,			'MLRF1'  ; ...
          ...
          'PEVF1' ,			'PVGF1'  ; ...
          ...
          '42076' ,			'CRYF1'  ; ...
          ...
          'SRVI' ,			'SRVI2'  ; ...
          'SRVI1' ,			'SRVI2'  ; ...
      };

  if ( exist('findAliases','var') && findAliases )
    colhdr = translate_station_name(colhdr);
    findix = find(strcmpi(stns(:,2), colhdr));
    stn = stns(findix,1);
    stn = { stn{:} colhdr{:} };

  else
    if ( ~iscell(colhdr) )
      colhdr = {colhdr};
    end;

    % If no translation found, use the column heading instead
    stn = strtrim(colhdr);
    for ix = 1:size(stns, 1)
      findix = find(strcmpi(stns{ix, 1}, stn));
      if ( ~isempty(findix) )
        stn(findix) = {stns{ix,2}};
      end;
    end;
  end;

return;
