function rng = valid_var_range(var)
%function rng = valid_var_range(var)
%
% If there is a consistent, known range of "good" values for a sensor, look
% that range up based on the sensor full name (see translate_var_name.m).
% Returns a 2x1 vector of [lowest highest]; DEFAULT is [-inf +inf].
%
% Last Saved Time-stamp: <Thu 2010-12-16 19:07:42  lew.gramer>
%

  persistent rngs;
  rngs = ...
      { ...
          'air_t'			[ 1	40 ] ; ...
          'air_t_dewp'			[ 1	40 ] ; ...
          'barom'			[ 980	1040 ] ; ...
          'fluor'			[ -inf	inf ] ; ...
          'licor_surf_par'		[ 0	3000 ] ; ...
          'licor_shallow_par'		[ 0	2000 ] ; ...
          'bic_surf_par'		[ 0	3000 ] ; ...
          'bic_shallow_par'		[ 0	2000 ] ; ...
          'bic_deep_par'		[ 0	2000 ] ; ...
          'barom_surf'			[ 980	1040 ] ; ...
          'ct_shallow_cond'		[ 20	80 ] ; ...
          'ct_shallow_salinity'		[ 10	50 ] ; ...
          'ct_shallow_seatemp'		[ 1	40 ] ; ...
          'xmissometer'			[ -inf	inf ] ; ...
          'sea_t'			[ 1	40 ] ; ...
          'wind1_dir'			[ 0	360 ] ; ...
          'wind2_dir'			[ 0	360 ] ; ...
          'wind1_gust'			[ 0	100 ] ; ...
          'wind2_gust'			[ 0	100 ] ; ...
          'wind1_speed'			[ 0	100 ] ; ...
          'wind2_speed'			[ 0	100 ] ; ...

          'ctd_shallow_cond'		[ 20	80 ] ; ...
          'ctd_shallow_seatemp'		[ 1	40 ] ; ...
          'ctd_shallow_seapres'		[ 0	10 ] ; ...
          'ctd_shallow_i_depth'		[ 0	10 ] ; ...
          'ctd_shallow_salinity'	[ 10	50 ] ; ...

          'ctd_deep_cond'		[ 20	80 ] ; ...
          'ctd_deep_seatemp'		[ 1	40 ] ; ...
          'ctd_deep_seapres'		[ 0	10 ] ; ...
          'ctd_deep_i_depth'		[ 0	10 ] ; ...
          'ctd_deep_salinity'		[ 10	50 ] ; ...

          'wxt_wgust'			[ 0	100 ] ; ...
          'wxt_wspeed'			[ 0	100 ] ; ...
          'wxt_wdir'			[ 0	360 ] ; ...
          'wxt_air_t'			[ 1	40 ] ; ...
          'wxt_humid'			[ 0	100 ] ; ...
          'wxt_barom'			[ 970	1040 ] ; ...
          'wxt_rain_amt'		[ 0	100 ] ; ...
          'wxt_rain_dur'		[ 0	inf ] ; ...
          'wxt_rain_max_int'		[ 0	inf ] ; ...
          'wxt_rain_avg_int'		[ 0	inf ] ; ...
          'wxt_hail_amt'		[ 0	inf ] ; ...
          'wxt_hail_dur'		[ 0	inf ] ; ...
          'wxt_hail_max_int'		[ 0	inf ] ; ...
          'wxt_hail_avg_int'		[ 0	inf ] ; ...

          'sami_seatemp'		[ 1	40 ] ; ...
          'sami_pco2'			[ 100	800 ] ; ...
          'sami_i434'			[ 0	inf ] ; ...
          'sami_i620'			[ 0	inf ] ; ...
          'sami_i740'			[ 0	inf ] ; ...
          'sami_k434'			[ 0	inf ] ; ...
          'sami_k620'			[ 0	inf ] ; ...

          'amodis_chlor_a'		[ 0	20 ] ; ...
          'amodis_seadas_sst'		[ 1	40 ] ; ...
          'tmodis_chlor_a'		[ 0	20 ] ; ...
          'tmodis_seadas_sst'		[ 1	40 ] ; ...
          'seawifs_chlor_a'		[ 0	20 ] ; ...

      };

  rng = [-inf inf];
  idx = find(strcmpi(rngs(:, 1), var));
  if ( ~isempty(idx) )
    rng = rngs{idx, 2};
  end;

return;
